### ISSUE TITLE
Forking daemon from ADB shell

### ISSUE THREAD

**Issue by mirfatif** [MuntashirAkon/libadb-android#1]
> For the safety of your app and its users, open a remote service instead of using ADB all the time and ask the user to stop or kill the ADB daemon.

`adbd` runs as an `init` service which is stopped when USB / Wireless debugging is turned off in Developer Options. And when an `init` service is stopped, all processes forked from it [get killed](https://android.googlesource.com/platform/system/core/+/refs/tags/android-12.0.0_r1/init/service.cpp#728) because they belong to the same cgroup (`cpuacct` or `memcg`). So it's not possible to keep any background process - which is forked from `adbd` by executing commands through ADB shell protocol - running while `adbd` itself is stopped.

**Comment by MuntashirAkon** [comment]
Yes, you cannot turn off **USB Debugging**. So, I guess I phrased it wrong. What I meant is that the users should be asked to disable ADB over TCP (but not ADB over Networks in LOS if used) or Wireless Debugging (only keeping USB debugging enabled).

**Comment by mirfatif** [comment]
I think turning off Wireless Debugging (when USB Debugging is enabled) would restart the `adbd` process (after un-setting `service.adb.tcp.port` property), so killing the background processes if any. Didn't test though.

**Comment by MuntashirAkon** [comment]
> I think turning off Wireless Debugging (when USB Debugging is enabled) would restart the `adbd` process (after un-setting `service.adb.tcp.port` property), so killing the background processes if any. Didn't test though.

Wireless debugging doesn't restart `adbd`, others do.

**Comment by mirfatif** [comment]
Please see if you want to merge this: https://github.com/mirfatif/libadb-android/commit/05894f260996026ac8fdaef43c40ad95a3bc6fad
I won't have to maintain git and gradle modules :)

**Comment by MuntashirAkon** [comment]
> Please see if you want to merge this: [mirfatif@05894f2](https://github.com/mirfatif/libadb-android/commit/05894f260996026ac8fdaef43c40ad95a3bc6fad)

Yeah, why not? Please sign-off your commit and submit a PR.

**Comment by mirfatif** [comment]
```
public interface OnAdbDaemonDiscoveredListener {
        void onPortChanged(@NonNull InetAddress hostAddress, int port);
    }
```
`NonNull` [here](https://github.com/MuntashirAkon/libadb-android/blob/2.1.0/libadb/src/main/java/io/github/muntashirakon/adb/android/AdbMdns.java#L44) is not correct. It can be null on service lost e.g. when pairing dialog is closed without successfully pairing. See [this](https://android.googlesource.com/platform/packages/modules/Connectivity/+/23651306c31b6fa18352d4a3ffb803f9a19f0105/service-t/src/com/android/server/NsdService.java#471).
